---
Name: mysite-config
After: 'framework/*','cms/*'
---
SSViewer:
  source_file_comments: false
  theme_enabled: false
SiteTree:
  nested_urls: true
  create_default_pages: false
Email:
  admin_email: 'info@stripecon.eu'

PiwikExtension:
  piwik_server: '//piwik.stripecon.eu/'
  piwik_site_id: 7


---
Only:
  environment: 'dev'
---
DataObjectAnnotator:
  enabled:
    true
  enabled_modules:
    - mysite
DebugBar:
  check_local_ip: false
